name: GitHub Issue → Jira Task

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write   # 코멘트 남기기

jobs:
  gh-issue-to-jira:
    runs-on: ubuntu-latest

    steps:
      # 0) Jira 로그인
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        with:
          base-url: ${{ secrets.JIRA_BASE_URL }}
          email: ${{ secrets.JIRA_USER_EMAIL }}
          api-token: ${{ secrets.JIRA_API_TOKEN }}

      # 1) Jira 이슈 생성
      - name: Create Jira issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: ${{ vars.JIRA_PROJECT_KEY }}
          issuetype: Task
          summary: '${{ github.event.issue.title }}'
          description: |
            *GitHub Issue*: ${{ github.event.issue.html_url }}
            *Author*: ${{ github.event.issue.user.login }}
            ----
            *Issue Body*:
            {{code}}
            ${{ github.event.issue.body }}
            {{code}}

      # 2) GitHub 이슈에 Jira 링크 코멘트 남기기
      - name: Comment back with Jira link
        uses: actions/github-script@v7
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        with:
          script: |
            const issueKey = '${{ steps.create.outputs.issue }}';
            const base = process.env.JIRA_BASE_URL.replace(/\/$/, '');
            const jiraUrl = `${base}/browse/${issueKey}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: `Jira issue created: **${issueKey}** → ${jiraUrl}`
            });
